project:
  type: website
  output-dir: docs

website:
  title: "SAMBA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - workshop.qmd  
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

author:
  - name: Daniela Dunkler
    affiliation: Medical University of Vienna, Center for Medical Data Science
date: last-modified                            
categories: [SAMBA, Medical University of Vienna, Vienna, Statistical modeling, Cardiovascular outcomes]
description: ""

